[package]
name = 'ThalaProtocol'
version = "1.0.0"

[addresses]
thala_protocol_interface = "092e95ed77b5ac815d3fbc2227e76db238339e9ca43ace45031ec2589bea5b8c"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.FixedPoint64]
git = "https://github.com/ThalaLabs/fixed_point64.git"
rev = "main"
